services:
  postgres-lab:
    image: postgres:16
    container_name: postgres_lab
    environment:
      POSTGRES_DB: "fundamentals"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres-spring-lab:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-spring-lab: